# Generated by Django 4.2 on 2025-06-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroCliente', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
    ]
